version: "3.1"
services:
  nginx:
    image: nginx:alpine
    working_dir: /src
    restart: always
    volumes:
      - ./build:/src
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
